version: '3'
services:
  postgres-space:
    container_name: space-service-db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: event-space
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "10000:5432"
    volumes:
      - space:/data/postgres

volumes:
  space: