spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:space_service}
    username: ${DATABASE_USERNAME:k_app}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update


application:
  title: Project For SWE
  version: 1.0.0 