spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:10000}/${DB_NAME:event-space}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
  flyway:
    create-schemas: true
    default-schema: order_unit
storage:
  directory: ${STORAGE_DIR:upload-dir}

application:
  title: Project For SWE
  version: 1.0.0

springdoc:
  api-docs:
    enabled: true
    path: /order-api
  swagger-ui:
    path: /swagger

security:
  jwt: ${JWT_SECRET:here_is_the_jwt_secret_override_it_please!}





