CREATE TABLE order_unit.space
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    address          VARCHAR(255),
    location         VARCHAR(255),
    size             INTEGER,
    max_capacity     INTEGER,
    base_rental_cost DOUBLE PRECISION,
    image_url        VARCHAR(255),
    CONSTRAINT pk_space PRIMARY KEY (id)
);