CREATE SCHEMA order_unit

CREATE TABLE order_unit.slot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    space_id   BIGINT                                  NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE,
    is_booked  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_slot PRIMARY KEY (id)
);

CREATE TABLE order_unit.space
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    address          VARCHAR(255),
    location         VARCHAR(255),
    size             INTEGER,
    max_capacity     INTEGER,
    base_rental_cost DOUBLE PRECISION,
    image_url        VARCHAR(255),
    CONSTRAINT pk_space PRIMARY KEY (id)
);

ALTER TABLE order_unit.slot
    ADD CONSTRAINT FK_SLOT_ON_SPACE FOREIGN KEY (space_id) REFERENCES order_unit.space (id);